{
 "title": "Single Of Panel Glass - Web Banking",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "NODE",
    "label": "Node",
    "query": {
     "query": "label_values(node_exporter_build_info{job=\"node-exporter\"},instance)"
    }
   },
   { "name": "NAMESPACE", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "POD",
    "label": "Pod Name",
    "query": {
     "query": "label_values({container_label_io_kubernetes_pod_namespace=\"$NAMESPACE\"},container_label_io_kubernetes_pod_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Web Banking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "/auth- requests (success vs failure)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg(web_banking_auth_total{result=\"attempts\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "web_banking_auth_total{result=\"failure\"}",
     "legendFormat": "failure"
    },
    {
     "expr": "web_banking_auth_total{result=\"success\"}",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "/transfer- requests (success vs failure)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "web_banking_transaction_status", "legendFormat": "requests" },
    {
     "expr": "web_banking_transaction_status{status=\"success\"}",
     "legendFormat": "success"
    },
    {
     "expr": "web_banking_transaction_status{status=\"failure\"}",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "web_banking_account_balance{account_id=\"123456\"}",
     "legendFormat": "source"
    },
    {
     "expr": "web_banking_account_balance{account_id=\"789012\"}",
     "legendFormat": "destination"
    }
   ]
  },
  {
   "title": "Transfers - Last values ​​sent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "web_banking_transaction_amount{source_account_id=\"123456\"}",
     "legendFormat": "amount"
    }
   ]
  },
  {
   "title": "Transfers - Source Account Balance ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "web_banking_account_balance{account_id=\"123456\"}",
     "legendFormat": "amount"
    }
   ]
  },
  {
   "title": "Transfers - Destination  Account Balance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "web_banking_account_balance{account_id=\"789012\"}",
     "legendFormat": "amount"
    }
   ]
  },
  {
   "title": "Trace - Requests Workflow Duration",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "targets": [
    { "service": "digital-bank" }
   ]
  },
  {
   "title": "By Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"cpu\"}) * 100",
     "legendFormat": "max capacity"
    },
    {
     "expr": "sum(container_cpu_usage_seconds_total{container_label_io_kubernetes_pod_name=~\"$POD\"}) by (container_label_io_kubernetes_pod_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_cpu_usage_seconds_total{container_label_io_kubernetes_pod_name=~\"$POD\"}) by (container_label_io_kubernetes_pod_name)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"$POD\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{pod=~\"$POD\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"memory\"})",
     "legendFormat": "max capacity"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{container_label_io_kubernetes_pod_name=~\"$POD\"}) by (container_label_io_kubernetes_pod_name)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_label_io_kubernetes_pod_name=~\"$POD\"}) by (container_label_io_kubernetes_pod_name)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"$POD\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{pod=~\"$POD\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_rss{container_label_io_kubernetes_pod_name=~\"$POD\"}) by (container_label_io_kubernetes_pod_name)"
    },
    {
     "expr": "sum(container_memory_cache{container_label_io_kubernetes_pod_name=~\"$POD\"}) by (container_label_io_kubernetes_pod_name)"
    },
    {
     "expr": "sum(container_memory_swap{container_label_io_kubernetes_pod_name=~\"$POD\"}) by (container_label_io_kubernetes_pod_name)"
    }
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{container_label_io_kubernetes_pod_name=~\"$POD\"}[5m])) by (container_label_io_kubernetes_pod_name)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{container_label_io_kubernetes_pod_name=~\"$POD\"}[5m])) by (container_label_io_kubernetes_pod_name)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "IOPS (Reads+Writes)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(sum by(container_label_io_kubernetes_pod_name) (rate(container_fs_reads_total{device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", container_label_io_kubernetes_pod_name=~\"$POD\"}[$__rate_interval]) + rate(container_fs_writes_total{device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", container_label_io_kubernetes_pod_name=~\"$POD\"}[$__rate_interval])))",
     "legendFormat": "{{container_label_io_kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "By Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Memory Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "instance:node_memory_utilisation:ratio{job=\"node-exporter\", instance=~\"$NODE\"} != 0",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "instance:node_cpu_utilisation:rate5m{job=\"node-exporter\", instance=~\"$NODE\"} != 0",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{job=\"node-exporter\", instance=~\"$NODE\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\"}[$__rate_interval])",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{job=\"node-exporter\", instance=~\"$NODE\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\"}[$__rate_interval])",
     "legendFormat": "{{device}} written"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by (mountpoint) (node_filesystem_size_bytes{job=\"node-exporter\", instance=~\"$NODE\", fstype!=\"\", mountpoint!=\"\"})\n"
    },
    {
     "expr": "max by (mountpoint) (node_filesystem_avail_bytes{job=\"node-exporter\", instance=~\"$NODE\", fstype!=\"\", mountpoint!=\"\"})\n"
    }
   ]
  },
  {
   "title": "Node Disk IO Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "instance_device:node_disk_io_time_seconds:rate5m{job=\"node-exporter\", instance=~\"$NODE\"} != 0",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Utilisation (Bytes Receive/Transmit)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "instance:node_network_receive_bytes_excluding_lo:rate5m{job=\"node-exporter\", instance=~\"$NODE\"} != 0",
     "legendFormat": "Receive"
    },
    {
     "expr": "instance:node_network_transmit_bytes_excluding_lo:rate5m{job=\"node-exporter\", instance=~\"$NODE\"} != 0",
     "legendFormat": "Transmit"
    }
   ]
  }
 ]
}