---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-banking-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-banking-frontend
  template:
    metadata:
      labels:
        app: web-banking-frontend
    spec:
      containers:
      - name: web-banking-frontend
        image: web-banking-frontend:1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: web-banking-frontend-service
spec:
  selector:
    app: web-banking-frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-banking-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-banking-backend
  template:
    metadata:
      labels:
        app: web-banking-backend
    spec:
      containers:
      - name: web-banking-backend
        image: web-banking-backend:1.0
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: web-banking-backend-service
spec:
  selector:
    app: web-banking-backend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort

